backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "static/img" # Adjust based on your media storage location
public_folder: "/img" # URL path for accessing media

collections:
  - name: "config"
    label: "Site Configuration"
    delete: false # Prevents file deletion from the CMS
    editor:
      preview: false
    files:
      - label: "General Settings"
        name: "config"
        file: "hugo.toml" # Adjust the file location based on your Hugo structure
        fields:
          - { label: "Base URL", name: "baseURL", widget: "string" }
          - { label: "Language Code", name: "languageCode", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }